/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cs2103_util_Console */

#ifndef _Included_cs2103_util_Console
#define _Included_cs2103_util_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cs2103_util_Console
 * Method:    clr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cs2103_util_Console_clr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
